name: Build
on:
  push:
    branches:    
      - master
  pull_request:
    branches:    
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.x
      - name: Setup Git
        run: |
          git config --global user.email "kandisheng@163.com"
          git config --global user.name "Candison"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: deno bundle src/test.ts docs/index.html
      - name: Commit
        run: |
          git add -A
          git commit -m "Build"
      - name: Push
        run: git push origin master
