name: Test
on:
  push:
    branches:    
      - master
  pull_request:
    branches:    
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.x
      - name: Setup Git
        run: |
          git config --global user.email "kandisheng@163.com"
          git config --global user.name "Candison"
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: deno bundle app.ts index.js
      - name: Commit
        run: |
          git add -A
          git commit -m "Build"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}