name: Test
on:
  push:
    branches:    
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.x
      - run: deno bundle app.ts index.js
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}